version: '3.8'

services:
  # app:
  #   build: .
  #   ports:
  #   - 3000:3000
  #   depends_on:
  #     - redis
  #     - postgres
  #     - elasticsearch
  #   networks:
  #     - chat-app-network
  #   volumes:
  #     - .:/usr/src/app
  
  redis:
    image: redis:7.2-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - chat-app-network
  
  postgres:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: Passw@rd
      POSTGRES_DB: chat_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chat-app-network
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - chat-app-network
    restart: unless-stopped

  elasticsearch:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
        - rabbitmq-log:/var/log/rabbitmq
    networks:
      - chat-app-network

networks:
  chat-app-network:
    driver: bridge

volumes:
  redis-data:
  postgres-data:
  pgadmin-data:
  es-data:
  rabbitmq-data:
  rabbitmq-log: